### PR TITLE
add content to git/github page

### PR DESCRIPTION
**Pull request by loj**

### CODE REVIEW

**Comment by bpoldrack** [comment]
@laurakw : Did you intentionally close this?
I'm asking for two reasons: Your fork doesn't seem to exist anymore, so closing might be accidentally by deleting that fork. And furthermore I wonder why it wasn't merged a while ago already. Is there any dispute about it with @aqw or where you guys waiting for someone else to merge? Or is there a new version to come?

**Comment by aqw** [comment]
@bpoldrack Not sure if closing this was intentional, but her initial content was more of a temporary collection from other sources, so it wasn't intended to be merged (and the PR was opened prematurely, to become familiar with the process of opening a PR).

@laurakw once the new content is ready, squashing, and force pushing to this same branch will allow you to re-use this PR.

**Comment by loj** [comment]
@bpoldrack thanks for the heads up. Indeed, I didn't intend to close this. I'll re-open it once I've finished writing the content in the next couple days.

**Comment by bpoldrack** [comment]
Ok, cool.

**Pull request closed without merging**
